### ISSUE TITLE
[Bug] Build production displays a blank page

### ISSUE THREAD

**Issue by pmabiala** [creativetimofficial/ct-paper-kit-pro-react#14]
### Version
Node Js LTS v16.17
### Reproduction link
https://neuronal.bible/hotels-immo/
### Operating System
Mac
### Device
MacBook Air
### Browser & Version
Chrome
### Steps to reproduce
yarn build
Deploy with filezilla
Run , I got a blank page
### What is expected?
My page fully displayed as in local 
### What is actually happening?
Blank page

---

**Comment by sajadevo** [comment]
This issue is fixed on v1.3.2.
