### ISSUE TITLE
[Bug] Can't Resolve Font Package -- Cannot See Nucleo Icons

### ISSUE THREAD

**Issue by ghost** [creativetimofficial/ct-paper-kit-pro-react#2]
### Version
Latest
### Reproduction link
https://demos.creative-tim.com/paper-kit-pro-react/#/documentation/introduction
### Operating System
MacOSX
### Device
N/A
### Browser & Version
N/A
### Steps to reproduce
Follow start instructions including modification of scripts: 

Starting after following all directions yields: 

./src/assets/scss/paper-kit.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/paper-kit.scss)

Module not found: Can't resolve './fonts/nucleo-icons.eot' in '/Users/sethmartin/Projects/politicore/client/src/assets/scss'
### What is expected?
This should run and not crash
### What is actually happening?
The app cannot start

---

**Comment by einazare** [comment]
Hello there, @sethgoodluck ,

Thank you for your interest in working with our products.
I just made a quick test on this product and it seems to work just fine.
Could you please provide me with the following video:
- Download product from Creative-Tim
- Unzip the archive
- Open a terminal and go into the unzipped archive
- Run `npm install && npm start`

Waiting for the video.

Best,
Manu

**Comment by ghost** [comment]
Hey @EINazare -- Integrating the project into an existing project is where the issue arose. 
I've sidestepped the crash by doing absolute imports of the icons in the sass modules. 

However -- now the nucleo icons are not rendering on my version of the app. 
<img width="309" alt="Screen Shot 2019-10-03 at 11 03 47 PM" src="https://user-images.githubusercontent.com/55430175/66184857-4a406c00-e632-11e9-86b0-eee54d2933a0.png">
<img width="1184" alt="Screen Shot 2019-10-03 at 11 04 28 PM" src="https://user-images.githubusercontent.com/55430175/66184858-4a406c00-e632-11e9-8619-050556fe912c.png">

**Comment by ghost** [comment]
> Hello there, @sethgoodluck ,
> 
> Thank you for your interest in working with our products.
> I just made a quick test on this product and it seems to work just fine.
> Could you please provide me with the following video:
> 
>     * Download product from Creative-Tim
> 
>     * Unzip the archive
> 
>     * Open a terminal and go into the unzipped archive
> 
>     * Run `npm install && npm start`
> 
> 
> Waiting for the video.
> 
> Best,
> Manu

To be clear -- when I run your version of the app, it seems to work. 
But after having pulled all of the relevant assets into my project -- it does not.

**Comment by einazare** [comment]
Hello again, @sethgoodluck ,

Honestly, I do not know what to tell you.
If you do not keep our project structure, then the paths will fail.
All assets are there, but for example if we have the following paths
```
url("our-foler/path/to/asset")
```
And then you move the asset to "your-folder/asset", then it will fail, since our url is looking for this path: `our-foler/path/to/asset`, instead of the `your-folder/asset`.

Hope this clears a bit your question.

Best,
Manu

**Comment by ghost** [comment]
Yes, but if I update all of those paths -- that shouldn't be an issue. 
What's odd is that everything works well on the cloned version of the repo.

@EINazare could you try the following when you have the opportunity?

1. Make a new directory (call it "test") and cd into it 
2. create-react-app "client" inside the test directory to instantiate a new react project 
3. Move your paper-kit folders and files (maintaining relative file structure) into the new directory 
4. Try to run the app 

I only run into issues when I start pulling the assets into my project (same file directory is maintained). Not totally sure why yet.  I'm wondering if there is some kind of dependency issue (as the project I'm trying to pull the assets into has latest for a lot of things)

**Comment by ghost** [comment]
Alright - after some digging, it is definitely a dependency issue. 

Testing a few things, a clean pull of your repo crashes as stated above if I do a package upgrade to latest.

Repro steps:

1. Download fresh repo
2. Upgrade packages to latest with yarn or npm
3. Cannot open or start the application without the error: 

```
Failed to compile.

./src/assets/scss/paper-dashboard.scss?v=1.1.0 (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-4!./src/assets/scss/paper-dashboard.scss?v=1.1.0)

Module not found: Can't resolve './fonts/nucleo-icons.eot' in '/Users/sethmartin/Projects/paperdash/src/assets/scss'
```

So, if someone is using this project inside of one of theirs -- they need to be careful with it as it is not compatible with the latest versions of  sass/create-react-app

**Comment by einazare** [comment]
Hello again, @sethgoodluck ,

I did not know that you have changed our package.json.
Yes indeed, if you change our dependencies, the product will break.
You need to keep our dependencies and wait for our updates.

Best,
Manu

**Comment by ghost** [comment]
Yes, I've been working on my own project (own json file and dependencies)
and wanted to use pages and elements of your product in it

We had several shared dependencies and this was causing version conflicts.

After adjusting the dependencies in my existing project to match the
versions of those in your product's json file, I've been able to proceed
fairly easily. No problems!

I appreciate your responsiveness nonetheless.

It is probably worthwhile to add a note in your product docs about
integrating your product with an existing one and the need to match
dependency versions for stability/functionality as some dependencies when
installed directly (yarn add someDependency) install incompatible
versions!

---

That all aside, lovely set of products. The code is largely clean and
fairly well organized (with helpful comments here and there as well).

Definitely worth the buy

**Comment by einazare** [comment]
Hello again, @sethgoodluck ,

Will add in our next update.

Best,
Manu

**Comment by syrakozz** [comment]
hi plz any workaround for this i need to update react

**Comment by ghost** [comment]
@syrakozz 
There are several packages that their product uses that you need to match versions on. 

Have a look at their `package.json` file.
You'll notice several packages with version strings next to them. 

You need to make whatever packages you share match their file.

You can do this with the command: `npm install SomeRandomPackage@x.x.x` or `yarn add SomeRandomPackage@x.x.x` to specify the versions. 

Since the issue is around the nucleo icons and sass files, I'd recommend starting with: 
`yarn add node-sass@4.12.0` or `npm install node-sass@4.12.0` 

That being said, there may be other packages in there that you also need to match on to have it work. 

Hope that's helpful

**Comment by syrakozz** [comment]
thank you , 
i found the solution its just to connect the path of /fonts/nucleio-icon in the scss file

@font-face {
  font-family: 'nucleo-icons';
  src: url('./../../fonts/nucleo-icons.eot');
  src: url('./../../fonts/nucleo-icons.eot') format('embedded-opentype'), url('./../../fonts/nucleo-icons.woff2') format('woff2'), url('./../../fonts/nucleo-icons.woff') format('woff'), url('./../../fonts/nucleo-icons.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
in paper-dashboard.scss

**Comment by geobehr** [comment]
I have the same problem and none of the above solutions work. When I did a clean install of Paper React Pro zip, then ran 'npm install', it found 2 moderate vulnerabilities. 
- if I just run 'npm start' without fixing 'npm audit fix', the site works
- Below is copy of 'npm audit' security report.
- If I DID run 'npm audit fix', the icon error occurred, and none of the above solutions worked for me. 
                       === npm audit security report ===
# Run  npm install react-scripts@3.3.0  to resolve 1 vulnerability
  Moderate        Cross-Site Scripting
  Package         serialize-javascript
  Dependency of   react-scripts

  Path            react-scripts > terser-webpack-plugin > serialize-javascript

  More info       https://npmjs.com/advisories/1426

# Run  npm update terser-webpack-plugin --depth 3  to resolve 1 vulnerability
  Moderate        Cross-Site Scripting
  Package         serialize-javascript

  Dependency of   react-scripts
  Path            react-scripts > webpack > terser-webpack-plugin >
                  serialize-javascript

  More info       https://npmjs.com/advisories/1426

found 2 moderate severity vulnerabilities in 906799 scanned packages
  run `npm audit fix` to fix 2 of them.

**Comment by einazare** [comment]
Hello there, @georgembehr ,

Thank you for your guidance and your solutions.
We'll make an update to our products first thing in January next year (2020).

Best,
Manu

**Comment by anhouchaimi** [comment]
didnt fix it ?? why stand behind some thing that causes people trouble ! update it!

**Comment by einazare** [comment]
Hello there, @anhouchaimi ,

Please provide me with the following video:
* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run `node -v`
* Run `npm -v`
* [If on Linux/Ubuntu/Mac system] Run `npm run install:clean`
* [If on Windows system] Run `npm install`
* [If on Windows system] Run `npm start`
* Showcase the issue

Will wait for the video.

Best,
Manu

**Comment by anhouchaimi** [comment]
scrapped it started from scratch on another template, cant afford to work on something for 2 days then it go sideways again. 
thanks though.

**Comment by DeepeshKr** [comment]
The solution for me was;

@font-face {
  font-family: 'nucleo-icons';
  src: url('./../../../../fonts/nucleo-icons.eot');
  src: url('./../../../../fonts/nucleo-icons.eot') format('embedded-opentype'), 
  url('./../../../../fonts/nucleo-icons.woff2') format('woff2'), 
  url('./../../../../fonts/nucleo-icons.woff') format('woff'), 
  url('./../../../../fonts/nucleo-icons.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}

It worked, but i wish i had a better or simpler way to solve this!

I also thought jsconfig.json should have helped

**Comment by kriscodes2** [comment]
@DeepeshKr I have been experimenting with this fix because it continues to occur for me. If you add the extra "../../../../" to the url on my windows 10 machine using git-bash on VS-code each line must be added in a specific order namely:

1st   =  src: url('./../../../../fonts/nucleo-icons.eot');
2nd  =  src: url('./../../../../fonts/nucleo-icons.eot') format('embedded-opentype'),
3rd  =   url('./../../../../fonts/nucleo-icons.ttf') format('truetype');
4th  =   url('./../../../../fonts/nucleo-icons.woff') format('woff'),
5th  =   url('./../../../../fonts/nucleo-icons.woff2') format('woff2'),

or else I enter a labyrinth of adding enough "../" to point outside the source directory where the compiler skips the error in favor of a more significant one and starts over.

Also the only real fix I have found was to scrap the program and start over from the original zip file provided then manually add my files over and over!!! Then of course reconnect the backend. Not the best fix but thank you for keeping me going.

**Comment by ewirth** [comment]
> 
> 
> Hello again, @sethgoodluck ,
> 
> I did not know that you have changed our package.json.
> Yes indeed, if you change our dependencies, the product will break.
> You need to keep our dependencies and wait for our updates.
> 
> Best,
> Manu

I have the same error with Now UI Dashboard PRO React :/

**Comment by einazare** [comment]
Hello there, @ewirth ,

Please go inside the scss folder, and replace all `../fonts` occurrences with `~assets/fonts`.

Let me know if that worked for you.

Best,
Manu

**Comment by ewirth** [comment]
Dear @EINazare , Manu,

I have checked the folder '\src\assets\scss\' which only contains:
- now-ui-dashboard (folder)
- now-ui-dashboard.scss (file)

I temporary managed the problem with by deactivation of nucleo-outline in 'now-ui-dashboard.scss':
```
// Core CSS
@import "now-ui-dashboard/buttons";
@import "now-ui-dashboard/social-buttons";
@import "now-ui-dashboard/inputs";
@import "now-ui-dashboard/typography";
@import "now-ui-dashboard/misc";
@import "now-ui-dashboard/navbar";
@import "now-ui-dashboard/dropdown";
@import "now-ui-dashboard/alerts";
@import "now-ui-dashboard/images";
//@import "now-ui-dashboard/nucleo-outline";
@import "now-ui-dashboard/tables";
@import "now-ui-dashboard/footers";
@import "now-ui-dashboard/fixed-plugin";
```

Any idea on this?

**Comment by einazare** [comment]
Hello again, @ewirth ,

I think I wasn't very explicit myself.
Please revert your changes (i.e. activate the nucleo-outline back).
And then, go inside `src/assets/scss/now-ui-dashboard/_nucleo-outline.scss` and replace:
```
@font-face {
  font-family: "Nucleo Outline";
  src: url("../fonts/nucleo-outline.eot");
  src: url("../fonts/nucleo-outline.eot") format("embedded-opentype"),
    url("../fonts/nucleo-outline.woff2") format("woff2"),
    url("../fonts/nucleo-outline.woff") format("woff"),
    url("../fonts/nucleo-outline.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}
```
With
```
@font-face {
  font-family: "Nucleo Outline";
  src: url("~assets/nucleo-outline.eot");
  src: url("~assets/nucleo-outline.eot") format("embedded-opentype"),
    url("~assets/nucleo-outline.woff2") format("woff2"),
    url("~assets/nucleo-outline.woff") format("woff"),
    url("~assets/nucleo-outline.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}
```

This will do the trick.

Best,
Manu

**Comment by ewirth** [comment]
Thank you,
corrected similarly:

```
@font-face {
  font-family: "Nucleo Outline";
  src: url("~assets/fonts/nucleo-outline.eot");
  src: url("~assets/fonts/nucleo-outline.eot") format("embedded-opentype"),
    url("~assets/fonts/nucleo-outline.woff2") format("woff2"),
    url("~assets/fonts/nucleo-outline.woff") format("woff"),
    url("~assets/fonts/nucleo-outline.ttf") format("truetype");
  font-weight: normal;
  font-style: normal;
}
```

**Comment by kriscodes2** [comment]
Awesome. I had a workaround but your logic is undeniable and far more
elegant.  I love the fix for several products. Cant wait to dig in to the
Now-Ui Dashboard as well!

**Comment by Rashmi-278** [comment]
here's how I resolved it.

It's a loader issue. Add next.config.js file


// next.config.js 

const withPlugins = require("next-compose-plugins");
const withImages = require("next-images");
const withSass = require("@zeit/next-sass");
const withCSS = require("@zeit/next-css");
const withFonts = require("next-fonts");
const webpack = require("webpack");
const path = require("path");

module.exports = withFonts(
  withCSS(
    withImages(
      withSass({
        webpack(config, options) {
          config.module.rules.push({
            test: /\.(eot|ttf|woff|woff2)$/,
            use: {
              loader: "url-loader",
            },
          });
          config.resolve.modules.push(path.resolve("./"));
          return config;
        },
        sassOptions: {
          includePaths: [path.join(__dirname, 'styles')],
        }
      })
    )
  )
);
package info ,

"@zeit/next-css": "^1.0.1",
"@zeit/next-sass": "^1.0.1",
"next-fonts": "^1.4.0",
"node-sass": "^4.14.1",
"webpack": "^4.44.1",
"next-compose-plugins": "^2.2.0",
"next-images": "^1.3.1",
