### ISSUE TITLE
[Bug] none of the kit is working

### ISSUE THREAD

**Issue by farhanazam41** [creativetimofficial/ct-paper-kit-pro-react#6]
### Version
1.2.0
### Reproduction link
https://demos.creative-tim.com/paper-kit-pro-react/?_ga=2.59564973.1268404861.1598496004-1074414071.1598496004#/presentation
### Operating System
WIndows 10
### Device
Desktop
### Browser & Version
Chrome Version 84.0.4147.135 (Official Build) (64-bit)
### Steps to reproduce
1.N/A
### What is expected?
It is expected to run as given in the documentation
### What is actually happening?
its not running according to the documentation. I tried every step in the documentation but did not work: got this error after running npm install --g cross-env .

./src/index.js
Module not found: Can't resolve 'assets/css/bootstrap.min.css' in 'C:\Users\syedf\Desktop\New folder\src'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'

---

**Comment by einazare** [comment]
Hello there, @farhanazam41 ,

Thank you for your interest in working with our products.
I've just tested the product and everything worked fine.
Can you please make sure you have the latest version of NodeJS LTS installed?
Also, could you please make the following video:
* Download the product
* Unzip the product
* Open terminal and cd into the project
* Run node -v
* Run npm -v
* [Mac/Ubuntu/Linux] Run npm run install:clean
* [Widnows] Run npm install
* [Widnows] Run npm start
* Showcase the issue

And send it to manu@creative-tim.com.

Best,
Manu
