### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by krishns18** [creativetimofficial/ct-paper-kit-pro-react#7]
### Version
1.2.0
### Reproduction link
http://localhost:3000/
### Operating System
Windows
### Device
Laptop
### Browser & Version
Chrome Version 87.0.4280.67
### Steps to reproduce
create-react-app app-name
then in the index.js add CSS files after copying the files bootstrap.min.css and paper-kit.css as mentioned in the documentation
### What is expected?
No error
### What is actually happening?
./src/assets/css/paper-kit.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./src/assets/css/paper-kit.css)
Error: Can't resolve '~assets/fonts/nucleo-icons.eot' in '/Users/krishns18/SHAILESH/GIT_REPOS/shaileshkrishna.com/src/assets/css'

---

**Comment by einazare** [comment]
Hello there @krishns18 ,

Sorry for this issue. I will update the docs ASAP. You need all the assets folder, since the CSS one is using images and fonts from that folder.

Best,
Manu

**Comment by DeepakKapiswe** [comment]
I'm also experiencing the same issue, Please fix it
