### ISSUE TITLE
[Bug] Upgrading to react-scripts 4.0.1 (after security audit) breaks compile

### ISSUE THREAD

**Issue by nico-oculusd** [creativetimofficial/ct-paper-kit-pro-react#9]
### Version
1.2.0
### Reproduction link
http://localhost:3000
### Operating System
Linux
### Device
PC
### Browser & Version
Firefox 84.0.2 (64bit)
### Steps to reproduce
# confirm the security issues
$ yarn audit

# Upgrade as per normal React method:
$ yarn upgrade --latest react-scripts

# This will now break
$ yarn start

### What is expected?
The website is running with perhaps only some warnings
### What is actually happening?
ERROR output on the console:

Failed to compile.

./src/assets/scss/paper-kit.scss (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--5-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--5-oneOf-6-4!./src/assets/scss/paper-kit.scss)
Error: Can't resolve '{{ path-general }}/assets/img{{ site.product_path }}/farid-askerov.jpg' in '/home/xxxxxx/src/assets/scss'
 

---
### Additional comments
From what I read on the vulnerabilities, it should be highly advisable to upgrade to the latest version of React. It does however seem this product may need some additional steps to facilitate an upgrade. Upgrade instructions and/or fixes will be most helpful.

**Comment by einazare** [comment]
Hello there, @nico-oculusd ,

Thank you for sharing this issue with us.
Please revert the react-scripts from version 4.x.x to the latest 3.x.x version.

Best,
Manu
